spring:
  profiles:
    active: dev  # 激活开发环境
---
server:
 port: 8003

mybatis:
 config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
 type-aliases-package: com.dfxt.springcloud.entities  # 所有Entity别名类所在包
 mapper-locations: classpath:mybatis/mapper/**/*.xml  # mapper映射文件
spring:
 profiles: dev
 application:
  name: microservice-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource 
  driver-class-name: com.mysql.cj.jdbc.Driver 
  url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8 
  username: root
  password: newpassword
  dbcp2:
   min-idle: 5 
   initial-size: 5 
   max-total: 5 
   max-wait-millis: 150 
eureka:
 client:
  registerWithEureka: true # 服务注册，false表示不将自已注册到Eureka服务中
  fetchRegistry: true # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
  serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
  # 单机版 Eureka 服务注册中心
  #defaultZone: http://localhost:6001/eureka
  # 集群版 Eureka 服务注册中心
   defaultZone: http://eureka6001.com:6001/eureka
 instance:
  instanceId: ${spring.application.name}:${server.port}-hystrix # 指定实例ID,就不会显示主机名了
  preferIpAddress: true #访问路径可以显示IP地址
---
server:
 port: 8003

mybatis:
 config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
 type-aliases-package: com.dfxt.springcloud.entities  # 所有Entity别名类所在包
 mapper-locations: classpath:mybatis/mapper/**/*.xml  # mapper映射文件
spring:
 profiles: prod
 application:
  name: microservice-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource 
  driver-class-name: com.mysql.cj.jdbc.Driver 
  url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8 
  username: root
  password: newpassword
  dbcp2:
   min-idle: 5 
   initial-size: 5 
   max-total: 5 
   max-wait-millis: 150 
eureka:
 client:
  registerWithEureka: true # 服务注册，false表示不将自已注册到Eureka服务中
  fetchRegistry: true # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
  serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
  # 单机版 Eureka 服务注册中心
  #defaultZone: http://localhost:6001/eureka
  # 集群版 Eureka 服务注册中心
   defaultZone: http://eureka6001.com:6001/eureka
 instance:
  instanceId: ${spring.application.name}:${server.port}-hystrix # 指定实例ID,就不会显示主机名了
  preferIpAddress: true #访问路径可以显示IP地址
      
      