spring:
  profiles:
    active: dev  # 激活开发环境
---
server:
  port: 6001   # 端口号
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka
    
eureka:
  instance:
    hostname: eureka6001.com
  client:
    registerWithEureka: false
    fetchResistry: false
    serviceUrl:
      defauleZone: http://eureka6001.com:6001/eureka/
  server:
    enable-self-preservation: false   #开发模式禁用自我保护机制
---
server:
  port: 6001  # 端口号
spring:
  profiles: prod   #生产环境
  application:
    name: springcloud-config-eureka
    
eureka:
  instance:
    hostname: eureka6001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serverUrl:
      defaultZone: http://eureka6001.com:6001/eureka/
  server:
    enable-selt-preservation: true  #生产环境开启自我保护机制